# Change these first
owner: vovastelmashchuk # Your GitHub organization or username, where this repository lives
repo: my-services-monitor # The name of this repository

sites:
  - name: MixDrinks
    url: https://mixdrinks.org/
  - name: AndroidStory
    url: https://androidstory.dev/
  - name: Nest2d
    url: https://nest2d.online/
  - name: Google (Added as target)
    url: https://www.google.com

status-website:
  cname: status.vovastelmashchuk.site
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Vova Stelmashchuk uptime
  introTitle: "**Upptime** of the Vova Stelmashchuk web service"
  introMessage: The uptime of [MixDrinks](https://mixdrinks.org/), [Nest2d](https://nest2d.online/), [Android story](https://androidstory.dev/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
